[extend]
useDefault = true

[allowlist]
paths = ['''\.env\.example$''', '''uv\.lock$''', '''package-lock\.json$''']
regexTarget = "line"
regexes = ['''recording_s3_(access|secret)_key''', '''key="[a-z0-9_]+"''']
